theme: minima
title: What I learnt!
description: Journal of concepts I learn while programming, building projects, or implementing solutions. 
header_pages:
  - about.md
  - portfolio.md
minima:
  skin: dark
  social_links:
    - { platform: github,  user_url: "https://github.com/tusharacc" }
    - { platform: linked, user_url: "https://www.linkedin.com/in/tushar-saurabh-49ba8a63/" }
